SELECT
    FIN.NUFIN,
    FIN.DHBAIXA,
    FIN.DTVENC,
    FIN.VLRDESDOS AS VALOR
FROM
    TGFFIN FIN
WHERE
    FIN.CODPARC =5291
    AND ( FIN.DHBAIXA IS NULL )
    AND FIN.RECDESP <> 0
    AND FIN.PROVISAO ='N'
ORDER BY
    FIN.DTVENC