SELECT
    TGFFIN.ABATIMENTO AS ABATIMENTO,
    TGFFIN.ABATIMENTOCAN AS ABATIMENTOCAN,
    TGFFIN.AD_LINHADIGITAVEL AS AD_LINHADIGITAVEL,
    TGFFIN.AGENCIA_CMC7 AS AGENCIA_CMC7,
    TGFFIN.ALIQICMS AS ALIQICMS,
    TGFFIN.AUTORIZADO AS AUTORIZADO,
    TGFFIN.BASEICMS AS BASEICMS,
    TGFFIN.BASEINSS AS BASEINSS,
    TGFFIN.BASEIRF AS BASEIRF,
    TGFFIN.BLOQVAR AS BLOQVAR,
    TGFFIN.CARTA AS CARTA,
    TGFFIN.CARTAODESC AS CARTAODESC,
    TGFFIN.CGC_CPF_CMC7 AS CGC_CPF_CMC7,
    TGFFIN.CHAVECTE AS CHAVECTE,
    TGFFIN.CHAVECTEREF AS CHAVECTEREF,
    TGFFIN.CLASSIFCESSAOOBRA AS CLASSIFCESSAOOBRA,
    TGFFIN.CODBARRA AS CODBARRA,
    TGFFIN.CODBCO AS CODBCO,
    TGFFIN.CODBCO_CMC7 AS CODBCO_CMC7,
    TGFFIN.CODCBE AS CODCBE,
    TGFFIN.CODCC AS CODCC,
    TGFFIN.CODCENCUS AS CODCENCUS,
    TGFFIN.CODCFO AS CODCFO,
    TGFFIN.CODCIDFIMCTE AS CODCIDFIMCTE,
    TGFFIN.CODCIDINICTE AS CODCIDINICTE,
    TGFFIN.CODCONTATO AS CODCONTATO,
    TGFFIN.CODCTABCOINT AS CODCTABCOINT,
    TGFFIN.CODEMP AS CODEMP,
    TGFFIN.CODEMPBAIXA AS CODEMPBAIXA,
    TGFFIN.CODFUNC AS CODFUNC,
    TGFFIN.CODIGOBARRA AS CODIGOBARRA,
    TGFFIN.CODLST AS CODLST,
    TGFFIN.CODMOEDA AS CODMOEDA,
    TGFFIN.CODNAT AS CODNAT,
    TGFFIN.CODOBRA AS CODOBRA,
    TGFFIN.CODPARC AS CODPARC,
    TGFFIN.CODPROJ AS CODPROJ,
    TGFFIN.CODTIPOPER AS CODTIPOPER,
    TGFFIN.CODTIPOPERBAIXA AS CODTIPOPERBAIXA,
    TGFFIN.CODTIPTIT AS CODTIPTIT,
    TGFFIN.CODTRIB AS CODTRIB,
    TGFFIN.CODUSU AS CODUSU,
    TGFFIN.CODUSUBAIXA AS CODUSUBAIXA,
    TGFFIN.CODUSUCOBR AS CODUSUCOBR,
    TGFFIN.CODVEICULO AS CODVEICULO,
    TGFFIN.CODVEND AS CODVEND,
    TGFFIN.CONTA_CMC7 AS CONTA_CMC7,
    TGFFIN.CUSTASPROCESSUAIS AS CUSTASPROCESSUAIS,
    TGFFIN.DEPOSITOJUDICIAL AS DEPOSITOJUDICIAL,
    TGFFIN.DESDOBDUPL AS DESDOBDUPL,
    TGFFIN.DESDOBRAMENTO AS DESDOBRAMENTO,
    TGFFIN.DESPADVOGADO AS DESPADVOGADO,
    TGFFIN.DESPCART AS DESPCART,
    TGFFIN.DHBAIXA AS DHBAIXA,
    TGFFIN.DHMOV AS DHMOV,
    TGFFIN.DHTIPOPER AS DHTIPOPER,
    TGFFIN.DHTIPOPERBAIXA AS DHTIPOPERBAIXA,
    TGFFIN.DIGSAFRA AS DIGSAFRA,
    TGFFIN.DTALTER AS DTALTER,
    TGFFIN.DTBAIXAPREV AS DTBAIXAPREV,
    TGFFIN.DTCONTAB AS DTCONTAB,
    TGFFIN.DTCONTABBAIXA AS DTCONTABBAIXA,
    TGFFIN.DTENTSAI AS DTENTSAI,
    TGFFIN.DTNEG AS DTNEG,
    TGFFIN.DTPRAZO AS DTPRAZO,
    TGFFIN.DTVENC AS DTVENC,
    TGFFIN.DTVENCINIC AS DTVENCINIC,
    TGFFIN.EXIGEISSQN AS EXIGEISSQN,
    TGFFIN.HISTORICO AS HISTORICO,
    TGFFIN.IDLOTEFDIC AS IDLOTEFDIC,
    TGFFIN.INSSRETIDO AS INSSRETIDO,
    TGFFIN.IRFRETIDO AS IRFRETIDO,
    TGFFIN.ISSRETIDO AS ISSRETIDO,
    TGFFIN.JUROSAVP AS JUROSAVP,
    TGFFIN.LINHADIGITAVEL AS LINHADIGITAVEL,
    TGFFIN.M2 AS M2,
    TGFFIN.MODELONFDES AS MODELONFDES,
    TGFFIN.MONIOCOREM AS MONIOCOREM,
    TGFFIN.MOTNAORETERISSQN AS MOTNAORETERISSQN,
    TGFFIN.NATUREZAOPERDES AS NATUREZAOPERDES,
    TGFFIN.NFCOMPLFIX AS NFCOMPLFIX,
    TGFFIN.NFENTSEQFIX AS NFENTSEQFIX,
    TGFFIN.NOMEEMITENTE_CMC7 AS NOMEEMITENTE_CMC7,
    TGFFIN.NOSSONUM AS NOSSONUM,
    TGFFIN.NROLOTEGNRE AS NROLOTEGNRE,
    TGFFIN.NUAPONTA AS NUAPONTA,
    TGFFIN.NUBCO AS NUBCO,
    TGFFIN.NUCCR AS NUCCR,
    TGFFIN.NUCOMPENS AS NUCOMPENS,
    TGFFIN.NUDEV AS NUDEV,
    TGFFIN.NUFIN AS NUFIN,
    TGFFIN.NUFTC AS NUFTC,
    TGFFIN.NUMBOR AS NUMBOR,
    TGFFIN.NUMCONTRATO AS NUMCONTRATO,
    TGFFIN.NUMDUPL AS NUMDUPL,
    TGFFIN.NUMNFSE AS NUMNFSE,
    TGFFIN.NUMNOTA AS NUMNOTA,
    TGFFIN.NUMOS AS NUMOS,
    TGFFIN.NUMPROCADMJUDIC AS NUMPROCADMJUDIC,
    TGFFIN.NUMREMESSA AS NUMREMESSA,
    TGFFIN.NUNOTA AS NUNOTA,
    TGFFIN.NUPED AS NUPED,
    TGFFIN.NURENEG AS NURENEG,
    TGFFIN.OBRACONSTCIVIL AS OBRACONSTCIVIL,
    TGFFIN.ORDEMCARGA AS ORDEMCARGA,
    TGFFIN.ORIGEM AS ORIGEM,
    TGFFIN.PARCRENEG AS PARCRENEG,
    TGFFIN.PDD AS PDD,
    TGFFIN.PROVISAO AS PROVISAO,
    TGFFIN.RATEADO AS RATEADO,
    TGFFIN.RECDESP AS RECDESP,
    TGFFIN.RECEBCARTAO AS RECEBCARTAO,
    TGFFIN.REGESPTRIBUT AS REGESPTRIBUT,
    TGFFIN.REJEICAOGNRE AS REJEICAOGNRE,
    TGFFIN.SEQUENCIA AS SEQUENCIA,
    TGFFIN.SERIENFDES AS SERIENFDES,
    TGFFIN.SERIENOTA AS SERIENOTA,
    TGFFIN.SITESPECIALRESP AS SITESPECIALRESP,
    TGFFIN.STATUSGNRE AS STATUSGNRE,
    TGFFIN.TIPJURO AS TIPJURO,
    TGFFIN.TIPMARCCHEQ AS TIPMARCCHEQ,
    TGFFIN.TIPMULTA AS TIPMULTA,
    TGFFIN.TPAGNFCE AS TPAGNFCE,
    TGFFIN.VALORPRESENTE AS VALORPRESENTE,
    TGFFIN.VLRALIBERAR AS VLRALIBERAR,
    TGFFIN.VLRBAIXA AS VLRBAIXA,
    TGFFIN.VLRCESSAO AS VLRCESSAO,
    TGFFIN.VLRCHEQUE AS VLRCHEQUE,
    TGFFIN.VLRDESC AS VLRDESC,
    TGFFIN.VLRDESCCALC AS VLRDESCCALC,
    TGFFIN.VLRDESCEMBUT AS VLRDESCEMBUT,
    TGFFIN.VLRDESDOB AS VLRDESDOB,
    TGFFIN.VLRFATCARTAO AS VLRFATCARTAO,
    TGFFIN.VLRINSS AS VLRINSS,
    TGFFIN.VLRIRF AS VLRIRF,
    TGFFIN.VLRISS AS VLRISS,
    TGFFIN.VLRJURO AS VLRJURO,
    TGFFIN.VLRJUROEMBUT AS VLRJUROEMBUT,
    TGFFIN.VLRJUROLIB AS VLRJUROLIB,
    TGFFIN.VLRJURONEGOC AS VLRJURONEGOC,
    TGFFIN.VLRMOEDA AS VLRMOEDA,
    TGFFIN.VLRMOEDABAIXA AS VLRMOEDABAIXA,
    TGFFIN.VLRMULTA AS VLRMULTA,
    TGFFIN.VLRMULTAEMBUT AS VLRMULTAEMBUT,
    TGFFIN.VLRMULTALIB AS VLRMULTALIB,
    TGFFIN.VLRMULTANEGOC AS VLRMULTANEGOC,
    TGFFIN.VLRPROV AS VLRPROV,
    TGFFIN.VLRVARCAMBIAL AS VLRVARCAMBIAL,
    TGFFIN.VLRVENDOR AS VLRVENDOR,
    (
        CASE
            WHEN TGFFIN.DTVENC IS NULL THEN 0
            ELSE (
                CASE
                    WHEN TGFFIN.DHBAIXA IS NOT NULL
                         AND TGFFIN.VLRBAIXA <> 0 THEN TRUNC( (TGFFIN.DHBAIXA) - (TGFFIN.DTVENC) )
                    ELSE TRUNC( (SYSDATE) - (TGFFIN.DTVENC) )
                END
            )
        END
    ) AS ATRASO,
    (
        CASE
            WHEN TGFFIN.DTVENCINIC IS NULL THEN 0
            ELSE (
                CASE
                    WHEN TGFFIN.DHBAIXA IS NOT NULL
                         AND TGFFIN.VLRBAIXA <> 0 THEN TRUNC( (TGFFIN.DHBAIXA) - (TGFFIN.DTVENCINIC) )
                    ELSE TRUNC( (SYSDATE) - (TGFFIN.DTVENCINIC) )
                END
            )
        END
    ) AS ATRASOINICIAL,
    (
        SELECT
            PAR.CGC_CPF
        FROM
            TGFPAR PAR
        WHERE
            PAR.CODPARC = TGFFIN.CODPARC
    ) AS CGC_CPF_PARC,
    (
        CASE
            WHEN TGFFIN.DHBAIXA IS NOT NULL
                 AND TGFFIN.NUBCO IS NOT NULL THEN (
                SELECT
                    ( ( ( 'Cód.Conta: '
                          || CAST(TSICTA.CODCTABCOINT AS VARCHAR(10) ) )
                        || ' - Descrição: ' )
                      || TSICTA.DESCRICAO )
                FROM
                    TSICTA,
                    TGFMBC
                WHERE
                    TGFMBC.NUBCO = TGFFIN.NUBCO
                    AND TSICTA.CODCTABCOINT = TGFMBC.CODCTABCOINT
            )
            ELSE NULL
        END
    ) AS CTABCOBAIXA,
    (
        CASE
            WHEN NVL(TGFFIN.NUDEV,0) <> 0 THEN (
                SELECT
                    MAX(ADC.DESCALINEACHEQDEV)
                FROM
                    TGFMDC MDC
                    INNER JOIN TGFADC ADC ON ( ADC.ALINEACHEQDEV = MDC.ALINEACHEQDEV )
                WHERE
                    MDC.NUDEV = TGFFIN.NUDEV
                    AND MDC.NUFINORIG = TGFFIN.NUFIN
            )
            ELSE NULL
        END
    ) AS DESCALINEACHEQDEV,
    (
        CASE
            WHEN NVL(TGFFIN.NFCOMPLFIX,0) <> 0 THEN (
                SELECT
                    CAB.NUMNOTA
                FROM
                    TGFCAB CAB
                WHERE
                    CAB.NUNOTA = TGFFIN.NFCOMPLFIX
            )
            ELSE NULL
        END
    ) AS NUMCOMPLFIX,
    (
        CASE
            WHEN TGFFIN.VLRDESDOB IS NOT NULL
                 AND TGFFIN.VLRDESDOB > 0 THEN ( ROUND(TGFFIN.VLRDESC / TGFFIN.VLRDESDOB * 100,2) )
            ELSE 0
        END
    ) AS PERCDESC,
    (
        CASE
            WHEN TGFFIN.DTVENC IS NOT NULL
                 AND TGFFIN.DTNEG IS NOT NULL THEN TRUNC( (TGFFIN.DTVENC) - (TGFFIN.DTNEG) )
            ELSE NULL
        END
    ) AS PRAZO,
    (
        CASE
            WHEN TGFFIN.DTVENCINIC IS NOT NULL
                 AND TGFFIN.DTNEG IS NOT NULL THEN TRUNC( (TGFFIN.DTVENCINIC) - (TGFFIN.DTNEG) )
            ELSE NULL
        END
    ) AS PRAZOINICIAL,
    (
        CASE
            WHEN TGFFIN.NUNOTA IS NOT NULL
                 AND TGFFIN.NUNOTA > 0 THEN (
                SELECT
                    CAB.RATEADO
                FROM
                    TGFCAB CAB
                WHERE
                    CAB.NUNOTA = TGFFIN.NUNOTA
            )
            ELSE 'N'
        END
    ) AS RATEADOCAB,
    (
        CASE
            WHEN NVL(TGFFIN.NFCOMPLFIX,0) <> 0 THEN (
                SELECT
                    CAB.SERIENOTA
                FROM
                    TGFCAB CAB
                WHERE
                    CAB.NUNOTA = TGFFIN.NFCOMPLFIX
            )
            ELSE NULL
        END
    ) AS SERIENOTACOMPL,
    ( ROUND( (NVL(TGFFIN.BASEICMS,0) * NVL(TGFFIN.ALIQICMS,0) ) / 100,2) ) AS VLRICMS,
    ( TGFFIN.VLRJURO + TGFFIN.VLRMULTA ) AS VLRJUROSMAISMULTA,
    ( ( NVL(TGFFIN.VLRDESDOB,0) + (
        CASE
            WHEN TGFFIN.TIPMULTA = '1' THEN NVL(TGFFIN.VLRMULTA,0)
            ELSE 0
        END
    ) + (
        CASE
            WHEN TGFFIN.TIPJURO = '1' THEN NVL(TGFFIN.VLRJURO,0)
            ELSE 0
        END
    ) + NVL(TGFFIN.DESPCART,0) + NVL(TGFFIN.VLRVENDOR,0) - NVL(TGFFIN.VLRDESC,0) - (
        CASE
            WHEN TGFFIN.IRFRETIDO = 'S' THEN NVL(TGFFIN.VLRIRF,0)
            ELSE 0
        END
    ) - (
        CASE
            WHEN TGFFIN.ISSRETIDO = 'S' THEN NVL(TGFFIN.VLRISS,0)
            ELSE 0
        END
    ) - (
        CASE
            WHEN TGFFIN.INSSRETIDO = 'S' THEN NVL(TGFFIN.VLRINSS,0)
            ELSE 0
        END
    ) - NVL(TGFFIN.CARTAODESC,0) + NVL( (
        SELECT
            SUM(I.VALOR * I.TIPIMP)
        FROM
            TGFIMF I
        WHERE
            I.NUFIN = TGFFIN.NUFIN
    ),0) + NVL(TGFFIN.VLRMULTANEGOC,0) + NVL(TGFFIN.VLRJURONEGOC,0) - NVL(TGFFIN.VLRMULTALIB,0) - NVL(TGFFIN.VLRJUROLIB,0) + NVL(TGFFIN.VLRVARCAMBIAL
,0) ) * NVL(TGFFIN.RECDESP,0) ) AS VLRLIQUIDO,
    ( NVL(TGFFIN.VLRDESDOB,0) + NVL(TGFFIN.VLRJURO,0) + NVL(TGFFIN.VLRMULTA,0) - NVL(TGFFIN.VLRDESC,0) ) AS VLRTOTALCALC,
    (
        CASE
            WHEN TGFFIN.VLRCHEQUE IS NOT NULL
                 AND TGFFIN.VLRCHEQUE <> 0
                 AND TGFFIN.VLRBAIXA IS NOT NULL THEN TGFFIN.VLRCHEQUE -
                CASE
                    WHEN TGFFIN.NUBCO IS NULL THEN TGFFIN.VLRBAIXA
                    ELSE (
                        SELECT
                            SUM(F.VLRBAIXA)
                        FROM
                            TGFFIN F
                        WHERE
                            F.NUBCO = TGFFIN.NUBCO
                    )
                END
            ELSE 0
        END
    ) AS VLRTROCO
FROM
    TGFFIN /*SQL_92_JOINED_TABLES*/
WHERE
    ( TGFFIN.NUFIN= 725417)