
SELECT 
PARCEIRO, 
RAZAOSOCIAL, 
DTCADASTRO, 
MESES_CAD, 
(LIMCRED-TOTAL_ABERTO) AS SALDO_LIMCRED,
LIMCRED, 
TOTALGERAL,
TOTAL_ABERTO,
NVL(TOTAL_ATRASO,0) AS TOTAL_ATRASO, 
PRAZOMEDIO, 

ATRASOMEDIO,
CASE WHEN MESES_CAD >0 THEN
ROUND(TOTALGERAL/MESES_CAD,2) ELSE TOTALGERAL END AS COMPRA_MEDIA, 
TOTAL_TITULO, 
EM_DIAS, 
ATRASO, 
ABERTO
,CASE WHEN  EM_DIAS > 0 THEN
ROUND((EM_DIAS*100)/(TOTAL_TITULO),2) ELSE 0 END AS PONTUALIDADE

FROM(

SELECT
    PAR.CODPARC AS PARCEIRO,
    PAR.DTCAD AS DTCADASTRO,
    ROUND((ROUND(SYSDATE-PAR.DTCAD,0)/30)*to_number(to_char(sysdate,'yyyy')-to_char(par.dtcad,'yyyy'))+1,0) AS MESES_CAD ,
    PAR.RAZAOSOCIAL AS RAZAOSOCIAL,
    PAR.LIMCRED AS LIMCRED,
    SUM (
    CASE WHEN FIN.DTVENC < SYSDATE-1  AND ( FIN.DHBAIXA IS NULL ) AND FIN.RECDESP <> 0 AND FIN.PROVISAO ='N' THEN FIN.VLRDESDOB END) AS TOTAL_ATRASO,
    SUM(FIN.VLRDESDOB) AS TOTALGERAL

   ,SUM(CASE  
   			WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
   			ELSE 0
   		END) AS TOTAL_ABERTO
  ,ROUND(SUM(FIN.VLRDESDOB * (DTVENC-DTNEG)) / SUM(FIN.VLRDESDOB),2) AS PRAZOMEDIO

  ,ROUND(SUM(FIN.VLRDESDOB * CASE (SIGN(CASE VLRBAIXA WHEN 0 THEN TRUNC(SYSDATE) - FIN.DTVENC ELSE TRUNC(FIN.DHBAIXA) - FIN.DTVENC END))
  								               WHEN 1 THEN (CASE VLRBAIXA WHEN 0 THEN TRUNC(SYSDATE) - FIN.DTVENC ELSE TRUNC(FIN.DHBAIXA) - FIN.DTVENC END)  
  								               ELSE 0
  							                END
             )/ SUM(FIN.VLRDESDOB),2) AS ATRASOMEDIO,


    COUNT(1) AS TOTAL_TITULO,
    SUM(CASE WHEN FIN.DHBAIXA <= FIN.DTVENC THEN 1 ELSE 0 END) AS EM_DIAS,
    SUM(CASE WHEN FIN.DHBAIXA > FIN.DTVENC or (FIN.DHBAIXA IS NULL AND FIN.DTVENC < SYSDATE) THEN 1 ELSE 0 END) AS ATRASO,
    SUM(CASE WHEN FIN.DHBAIXA IS NULL AND TRUNC(FIN.DTVENC) < SYSDATE THEN 1 ELSE 0 END) AS ABERTO

FROM
    TGFFIN FIN
  , TGFPAR PAR
  , TGFTIT

WHERE
      FIN.CODTIPTIT = TGFTIT.CODTIPTIT
  AND FIN.CODPARC = PAR.CODPARC
  AND PAR.CLIENTE = 'S'

  AND NOT (FIN.PROVISAO = 'S' AND FIN.DHBAIXA IS NOT NULL AND FIN.ORIGEM='E')
  AND FIN.VLRDESDOB <> 0
  AND (FIN.ORIGEM <> 'P' OR FIN.CODPARC = 1 OR 1 = 0)

  AND FIN.RECDESP = 1   --AND (FIN.DHBAIXA IS NULL  )--
  --AND FIN.CODPARC = 57



   GROUP BY 1,2,PAR.CODPARC, PAR.RAZAOSOCIAL,PAR.LIMCRED,PAR.DTCAD, ROUND(ROUND(SYSDATE-PAR.DTCAD,0)/30,0)) ORDER BY LIMCRED DESC
