SELECT DISTINCT
	PAR.NOMEPARC AS Nome_do_Parceiro,
	PAR.NUMEND AS Núm_End_Parc,
	ENDER.NOMEEND AS Endereço_do_Parceiro,
	FIN.NUFIN,
	ENDR.TIPO AS Tipo_End,
	FIN.DTNEG AS Dt_Negoc,
	FIN.DTVENC AS Dt_Vencto,
	PAR.CEP AS CEP,
	CID.NOMECID AS Nome_da_Cidade,
	UFS.UF AS UF,
	(FIN.VLRDESDOB - NVL(FIN.VLRJUROEMBUT,0) - NVL(FIN.VLRMULTAEMBUT,0)) * FIN.RECDESP AS Valor,
	PAR.COMPLEMENTO AS Complemento,
	CASE
		WHEN CAB.NUMNFSE IS NOT NULL THEN CAB.NUMNFSE
		ELSE TO_CHAR(FIN.NUMNOTA)
	END AS Nro_Nota,
	BAI.NOMEBAI AS Nome_do_Bairro,
	EMP.RAZAOSOCIAL AS RazaoSocial,
	CAB.NUNOTA,
	CAB.NUMNFSE,
	NFSE.CODVERIFNFSE
FROM TGFFIN FIN
LEFT JOIN TSIEMP EMP ON (EMP.CODEMP = FIN.CODEMP)
LEFT JOIN TGFPAR PAR ON (FIN.CODPARC = PAR.CODPARC)
LEFT JOIN TSIEND ENDER ON (PAR.CODEND = ENDER.CODEND)
LEFT JOIN TSIEND ENDR ON (PAR.CODEND = ENDR.CODEND)
LEFT JOIN TSICID CID ON (PAR.CODCID = CID.CODCID)
LEFT JOIN TSIUFS UFS ON (CID.UF = UFS.CODUF)
LEFT JOIN TSIBAI BAI ON (PAR.CODBAI = BAI.CODBAI)
LEFT JOIN TGFCAB CAB ON (CAB.NUNOTA = FIN.NUNOTA)
LEFT JOIN TGFNFSE NFSE ON (CAB.NUNOTA = NFSE.NUNOTA)
WHERE
	 FIN.CODEMP = 1 AND
	 FIN.DHBAIXA IS NULL  AND
	 FIN.DTVENC BETWEEN to_date('01/01/2018','DD/MM/YYYY') AND to_date('19/06/2018','DD/MM/YYYY') AND
	 FIN.RECDESP = 1 AND
	 FIN.PROVISAO = 'N' --AND
	 --PAR.CODPARC = 6614
ORDER BY Nome_do_Parceiro,Dt_Vencto