create or replace TRIGGER SANKHYA.TRG_UPD_INS_TGFPAR_PERF_FISC BEFORE UPDATE OR INSERT ON SANKHYA.TGFPAR FOR EACH ROW


DECLARE
     
BEGIN

    
	IF :NEW.CLASSIFICMS <> 'C' OR :NEW.CLASSIFICMS <> 'R' THEN 
    
        
        RAISE_APPLICATION_ERROR(-20101, 'Classificação ICMS só pode ser REVENDEDOR ou CONSUMIDOR FINAL NÃO CONTRIBUINTE');
        
        
    END IF;
 END;