


SELECT 
CAB.CODPARC,
CAB.CODVEND,
PAR.RAZAOSOCIAL,
round((NVL(SUM((((ITE.QTDNEG * ITE.VLRUNIT) + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC - ITE.VLRREPRED) )),0)/
(SELECT 
NVL(SUM((((ITE.QTDNEG * ITE.VLRUNIT) + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC - ITE.VLRREPRED) )),0) AS ITEM

FROM

TGFCAB CAB,
TGFITE ITE,
TGFPRO PR,
TGFVEN VEN,
TGFPAR PAR

WHERE
PAR.CODPARC = CAB.CODPARC 
AND CAB.NUNOTA = ITE.NUNOTA
AND CAB.CODVEND = VEN.CODVEND
AND ITE.CODPROD = PR.CODPROD
AND CAB.TIPMOV IN ('V')
AND CAB.STATUSNOTA = 'L'
AND (PR.CODGRUPOPROD >= 01 
AND PR.CODGRUPOPROD <= 5900000)
AND CAB.CODTIPOPER IN( 700, 703, 706, 707, 709, 715, 723,724, 725)
AND CAB.CODEMP = 1
AND CAB.CODVEND = :codvend 

AND TRUNC(CAB.DTFATUR) BETWEEN :dtini AND  :dtfim

))*100,2) as item,ROUND(RATIO_TO_REPORT(COUNT(*)) OVER()*100, 2)
FROM

TGFCAB CAB,
TGFITE ITE,
TGFPRO PR,
TGFVEN VEN,
TGFPAR PAR

WHERE
PAR.CODPARC = CAB.CODPARC 
AND CAB.NUNOTA = ITE.NUNOTA
AND CAB.CODVEND = VEN.CODVEND
AND ITE.CODPROD = PR.CODPROD
AND CAB.TIPMOV IN ('V')
AND CAB.STATUSNOTA = 'L'
AND (PR.CODGRUPOPROD >= 01 
AND PR.CODGRUPOPROD <= 5900000)
AND CAB.CODTIPOPER IN( 700, 703, 706, 707, 709, 715, 723,724, 725)
AND CAB.CODEMP = 1
AND CAB.CODVEND = :codvend

AND TRUNC(CAB.DTFATUR) BETWEEN :dtini AND  :dtfim

GROUP BY 
CAB.CODPARC,
CAB.CODVEND,
PAR.RAZAOSOCIAL

ORDER BY ITEM DESC