select 

codvend,
cod,
razaosocial,
item as valor,
round(SUM((item)) OVER (ORDER BY item desc ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),2) valor_acumulado,
peso,
perc as perc,
round(SUM((perc)) OVER (ORDER BY perc desc ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),2) perc_acumulado

from(

SELECT 
CAB.CODPARC AS COD,
CAB.CODVEND,
PAR.RAZAOSOCIAL,
NVL(SUM((((ITE.QTDNEG * ITE.VLRUNIT) + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC - ITE.VLRREPRED) )),0) as item,
NVL(SUM(PR.PESOLIQ*ITE.QTDNEG),0) as peso,
ROUND(RATIO_TO_REPORT(COUNT(*)) OVER()*100, 4) as perc
FROM

TGFCAB CAB,
TGFITE ITE,
TGFPRO PR,
TGFVEN VEN,
TGFPAR PAR

WHERE
PAR.CODPARC = CAB.CODPARC 
AND CAB.NUNOTA = ITE.NUNOTA
AND CAB.CODVEND = VEN.CODVEND
AND ITE.CODPROD = PR.CODPROD
AND CAB.TIPMOV IN ('V')
--AND PR.MARCA = 'ROYALCANIN'
AND CAB.STATUSNOTA = 'L'
AND (PR.CODGRUPOPROD >= 01 
AND PR.CODGRUPOPROD <= 5900000)
AND CAB.CODTIPOPER IN( 700, 703, 706, 707, 709, 715, 723,724, 725)
AND CAB.CODEMP = 1
AND CAB.CODPARC IN (SELECT RPV.CODPARC FROM TGFRPV RPV WHERE RPV.CODVEND = :codvend)

AND TRUNC(CAB.DTFATUR) BETWEEN SYSDATE - 150 AND  SYSDATE

GROUP BY 
CAB.CODPARC,
CAB.CODVEND,
PAR.RAZAOSOCIAL

ORDER BY ITEM DESC)