SELECT 

B.CODCID,
B.NOMECID,
B.UF,
B.POPULACAO,
--B.LATITUDE,
--B.LONGITUDE,
CASE WHEN A.REALIZADO>0 THEN 1 ELSE 2 END AS POSITIVADO,
NVL(A.REALIZADO,0) AS REALIZADO


FROM


(SELECT  
    PAR.CODCID,
    SUM(((ITE.QTDNEG * ITE.VLRUNIT) + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC - ITE.VLRREPRED) )  AS REALIZADO
    
FROM
    TGFCAB CAB,
    TGFITE ITE,
    TGFPRO PRO,
    TGFPAR PAR,
    TSICID CID,
    TGFTPP TPP
WHERE
    PAR.CODPARC = CAB.CODPARC AND
    PRO.CODPROD = ITE.CODPROD AND 
    CAB.NUNOTA = ITE.NUNOTA AND 
    PAR.CODTIPPARC = TPP.CODTIPPARC AND
    PAR.CODCID = CID.CODCID AND
    --TPP.CODTIPPARC  IN (10101001, 10101004, 10101008, 10101010) AND
    PRO.MARCA = 'ROYALCANIN' AND
    CID.UF  in (17, 10,26,19) AND
    CID.POPULACAO >= :POPULACAO  AND 
    CID.NOMECID NOT LIKE '%DEFIN%' AND
    --(cab.dtfatur between :dtini1 and :dtfim1) or 
    (cab.dtfatur BETWEEN :DTINI AND :DTFIM) AND
    CAB.CODTIPOPER IN ( 700, 703, 706, 707, 709, 715, 723,724, 725) AND
    CAB.TIPMOV IN ('V') AND
    CAB.STATUSNOTA = 'L' AND
    PRO.codgrupoprod between 01 AND  59999999 AND
    CAB.CODEMP = :codemp
    
    GROUP BY PAR.CODCID)A
    
    FULL OUTER JOIN
    (SELECT

        cid.codcid,
        cid.codmunfis, 
        CID.POPULACAO, 
        CID.LONGITUDE,
        CID.LATITUDE,
        CID.NOMECID,
        UFS.UF
    
    FROM 
    TSIUFS UFS,
    TSICID CID 
    
    WHERE 
    CID.UF = ufs.coduf AND 
    CID.POPULACAO >= :POPULACAO  AND 
    CID.NOMECID NOT LIKE '%DEFIN%' AND
    CID.UF in (17, 10,26,19)
    )B ON B.CODCID = A.CODCID --WHERE A.REALIZADO > 0 -- B.CODCID IS NOT NULL -- 17 RN 10 PE 26 PB 19
    --AND CODMUNFIS = 0
--AND B.CODCID <> 158
ORDER BY NOMECID