SELECT 

MARCAS,
NVL(VALOR,0) AS VALOR,
NVL(META,0) AS META


FROM

(SELECT
CODVEND,
MARCA,
SUM(VALOR) as VALOR,
CASE WHEN CODVEND =	3	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	4772.8128	
     WHEN MARCA =	'PETHERAPY'	THEN	500	
     WHEN MARCA =	'PETHYPRIME'	THEN	2096.7816	
     WHEN MARCA =	'SANITHYPRI'	THEN	15025.3824	
     WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

     
     WHEN CODVEND =	15	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	15636.05	
     WHEN MARCA =	'PETHERAPY'	THEN	500	
     WHEN MARCA =	'PETHYPRIME'	THEN	700	
     WHEN MARCA =	'SANITHYPRI'	THEN	2085.27	
     WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	30	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	6591.9606	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	768.4224	
WHEN MARCA =	'SANITHYPRI'	THEN	2200.5336	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 
                                       
           WHEN CODVEND =	42	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	8445.035088	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	2113.1304	
WHEN MARCA =	'SANITHYPRI'	THEN	3110.22	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 
                                            
           WHEN CODVEND =	31	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	1863.59544	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	2089.1208	
WHEN MARCA =	'SANITHYPRI'	THEN	1850	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	4	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	2363.23464	
WHEN MARCA =	'PETHERAPY'	THEN	1100	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	4771.392	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	1	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	1505.13376	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	7314.9384	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	17	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	1000	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	1627.0584	
WHEN MARCA =	'SANITHYPRI'	THEN	4341.8784	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	53	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	2342.537328	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	1842.2352	
WHEN MARCA =	'SANITHYPRI'	THEN	1850	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	39	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	10673.95337	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	3893.0184	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	20	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	1000	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	1850	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	19	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	2664.0768	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	1410.8976	
WHEN MARCA =	'SANITHYPRI'	THEN	1850	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	8	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	1578.81744	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	1573.8432	
WHEN MARCA =	'SANITHYPRI'	THEN	10582.1808	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	5	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	7859.522928	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	1500	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	16	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	5108.076552	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	1528.536	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	14	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	1000	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	1850	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	7	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	3693.161592	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	1850	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	49	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	2858.86272	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	1850	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 

           WHEN CODVEND =	12	THEN		
CASE WHEN  MARCA=	'MELODIAPET'	THEN	9761.901648	
WHEN MARCA =	'PETHERAPY'	THEN	500	
WHEN MARCA =	'PETHYPRIME'	THEN	700	
WHEN MARCA =	'SANITHYPRI'	THEN	1831.4472	
WHEN MARCA =	'ZOOPRIME'	THEN	2100	END 





                                            
                                            
                                            
                                            END AS META
FROM


(select 
VEN.CODVEND,
CASE WHEN
PR.MARCA IN ('MELODIAPET', 'BIOAVIS') THEN 'MELODIAPET' ELSE PR.MARCA END MARCA,
NVL(CASE WHEN
PR.MARCA IN ('MELODIAPET', 'BIOAVIS') THEN
NVL(SUM((((ITE.QTDNEG * ITE.VLRUNIT) + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC - ITE.VLRREPRED) )),0) ELSE 
NVL(SUM((((ITE.QTDNEG * ITE.VLRUNIT) + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC - ITE.VLRREPRED) )),0) END,0)  AS VALOR

FROM

TGFCAB CAB,
TGFITE ITE,
TGFPRO PR,
TGFVEN VEN

WHERE

    CAB.NUNOTA = ITE.NUNOTA
AND CAB.CODVEND = VEN.CODVEND
AND ITE.CODPROD = PR.CODPROD
AND PR.MARCA IN( 'MELODIAPET','BIOAVIS',	'PETHERAPY'	,'PETHYPRIME'	,'SANITHYPRI'	,'ZOOPRIME')
AND CAB.TIPMOV IN ('V')
AND CAB.STATUSNOTA = 'L'
AND (PR.CODGRUPOPROD >= 01 
AND PR.CODGRUPOPROD <= 5900000)
AND CAB.CODTIPOPER IN( 700, 703, 706, 707, 709, 715, 723,724, 725)
AND CAB.CODEMP = 1
AND cab.codvend = :codvend 
AND TRUNC(CAB.DTFATUR) BETWEEN :dtini AND :dtfim
GROUP BY  VEN.CODVEND,pr.marca) GROUP BY CODVEND,MARCA) A

FULL OUTER JOIN

(SELECT 

DISTINCT(PR.MARCA) AS MARCAS

FROM 

TGFPRO PR

WHERE 

PR.MARCA IN( 'MELODIAPET',	'PETHERAPY'	,'PETHYPRIME'	,'SANITHYPRI'	,'ZOOPRIME')) B ON B.MARCAS = A.MARCA

